# Generated by Django 4.2.30 on 2026-08-13 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('admn_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('student_class', models.CharField(db_column='class', max_length=10)),
                ('section', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='IssueRecord',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('admn_no', models.ForeignKey(db_column='admn_no', on_delete=django.db.models.deletion.CASCADE, to='library_app.student')),
                ('book_id', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='library_app.book')),
            ],
            options={
                'db_table': 'issue_records',
            },
        ),
    ]
